### PR TITLE
Update for ZC200

### PR DESCRIPTION
**Pull request by torvista**
That should do it.

### CODE REVIEW

**Comment by lat9** [comment]
OMG, @torvista, that's going to take me a long time to review.  Any chance of breaking this single PR into multiple ones with each addressing a _single_ update?

**Comment by torvista** [comment]
That was the intention with the separate PRs to the branch. To be honest only the FIXES have real changes in them.

**Comment by lat9** [comment]
The next version (v3.0.0) will start in the `3.0.0` branch.  That will support zc158 and zc200 and the responsive_classic and Bootstrap templates.

For zc158, the changes present in [this](https://github.com/zencart/zencart/pull/6336) zc200 PR will be needed for the plugin's operation.  That said, it's going to be a fairly major change, but I'll keep this PR open and make sure that the various changes provided are included!

**Comment by torvista** [comment]
That PR borked the shopfront. I've reverted the config.core for the moment.

**Comment by lat9** [comment]
> That PR borked the shopfront. I've reverted the config.core for the moment.

In what way?  I'll note that it's not compatible with the current 'state' of the Products' Pagination plugin.

**Comment by torvista** [comment]
PHP Fatal error:  Cannot declare class splitPageResults, because the name is already in use in \includes\classes\split_page_results.php on line 38
https://github.com/lat9/product_pagination/blob/74ac9248f0cb8982123dede839ffdbb6d2fbdad6/includes/classes/split_page_results.php#L38

**Comment by lat9** [comment]
As I said above; I'd just added that note for this PR to indicate that I'll be using the changes you provided as a _baseline_, but v3.0.0 of Products' Pagination will be **very different** from previous versions.

**Comment by torvista** [comment]
Sure, no rush.

**Comment by lat9** [comment]
Changes provided in this PR are now included in the v3.0.0 release; closing.

**Pull request closed without merging**
